### DISCUSSION TITLE
NAS Synology

### DISCUSSION THREAD

**Discussion by Homavi88** [masterking32/MasterCryptoFarmBot#27] [General]
Hello. I can't figure out how to run the bot on NAS Synology.
<img width="559" alt="Снимок экрана 2024-09-30 в 21 31 03" src="https://github.com/user-attachments/assets/8586f644-a22c-4181-af40-dea04261d6fc">

I uploaded everything to the folder and I'm trying to run the code/ through the command deadline. But there is an error.
I didn't create a visual environment.

**Comment by Fy0urM** [comment]
I think you need to install python3-pip yourself, or find a nas-appropriate package for it

**Reply by Homavi88** [reply]
As a result, I installed and launched everything, but when I try to run it, an error appears
<img width="914" alt="Снимок экрана 2024-09-30 в 21 52 53" src="https://github.com/user-attachments/assets/9bc0fe16-0f9c-4b34-ad72-3ce744e66324">

**Reply by Fy0urM** [reply]
1. make sure you have one version of python installed
`ls /usr/bin/python*`
2. make sure you have version 3.10+
`python3 --version`

**Reply by Homavi88** [reply]
> 1. make sure you have one version of python installed
>    `ls /usr/bin/python*`
> 2. make sure you have version 3.10+
>    `python3 --version`

That's right, version 3.8, but don't reinstall it

I'm trying to integrate it into Container Manager NAS Synology, but I can't create a yaml configuration (((

Do you have any experience how to create yaml on your project?

**Reply by Fy0urM** [reply]
Sorry, all I know about "Container Manager NAS Synology" is something like docker) try asking chatgpt

**Reply by Homavi88** [reply]
> Sorry, all I know about "Container Manager NAS Synology" is something like docker) try asking chatgpt

Chat gpt doesn't help in this matter. I managed to mount the image on NAS Synology, but it gives the following errors
<img width="1012" alt="Снимок экрана 2024-10-01 в 20 40 52" src="https://github.com/user-attachments/assets/92c0948e-f653-42e5-8eb9-69bdccdd76ed">

**Reply by Fy0urM** [reply]
I was able to put Synology NAS OS on vmware and run MCF in it. used DS920+ DSM 7.1.1-42962 Update 6. my OS did not have Synology Container Manager, only docker.
When installing docker a docker folder was created in the first volume of the storage, I set the mount point to `/volume1/docker/MasterCryptoFarmBot` on this path. but I did some preliminary configuration. 

1. added the community repository `https://packages.synocommunity.com/`
2. installed git from the community repository.
3. used the latest docker-compose.yml file that runs the sh script. put it in the docker folder via SFTP to avoid searching for it.
4. enable ssh in the settings and connect via ssh to the NAS
5. went to the docker folder, cloned the bot `git clone https://github.com/masterking32/MasterCryptoFarmBot.git`
6. configured the config.
7. changed the owner of the cloned repository `sudo chown -R root:root MasterCryptoFarmBot`
8. ran compose file `sudo docker-compose -f docker-compose.yml up`

ssh session can be closed, docker container will not stop. to connect to the container you need to connect via ssh and type `sudo docker exec -it mcf_container /bin/bash` where mcf_container is the name of the container itself. but access to the log will no longer be available. i don't know how to get it back) but this will allow `add_account.py` to be used to add pyrogram sessions

but there is access to the log from the docker application in the NAS panel (2 screenshot under spoiler)

<details>
<summary>screenshot</summary>

![image](https://github.com/user-attachments/assets/5d93ec29-ad1f-4f42-8c9a-955aef98dc5f)
</details>
<details>
<summary>docker application</summary>

![image](https://github.com/user-attachments/assets/95af9433-95df-48b2-9479-77302f3d4693)

</details>

<details>
<summary>used docker-compose.yml</summary>

```yml
version: '3.8'

services:
  python-container:
    image: python:3.12
    container_name: mcf_container
    restart: always
    volumes:
      - /volume1/docker/MasterCryptoFarmBot:/app/MasterCryptoFarmBot
    environment:
      - PYTHONUNBUFFERED=1
    working_dir: /app/MasterCryptoFarmBot
    ports:
      - "3232:3232"
    networks:
      - default

    init: true
    entrypoint: >
      sh -c '
      if ! command -v git &> /dev/null; then
        apt-get update && apt-get install -y git;
      fi &&
      if [ ! -f main.py ]; then
        git clone https://github.com/masterking32/MasterCryptoFarmBot.git ./;
      fi &&
      if [ ! -f config.py ]; then
        cp config.py.sample config.py
      fi &&
      if [ -f start_linux.sh ]; then
        echo "Launching...";
        bash start_linux.sh;
      fi'

networks:
  default:
    driver: bridge

```
</details>

**Reply by Fy0urM** [reply]
I modified the file a bit, it is no longer necessary to manually reassign the directory owner. the log appears in the docker application terminal. i don't know if it will work for you. for some reason docker in nas can't create a folder to which the application mounts, so it must be created in advance `/volume1/docker/MasterCombatFarmBot`

Ideally you don't even have to add a third-party repository and install the git, just create a MasterCryptoFarmBot folder in /volume1/docker

<details>
<summary>docker-compose.yml</summary>

```yml
version: '3.8'

services:
  python-container:
    image: python:3.12
    stdin_open: true
    tty: true
    command: /bin/bash
    container_name: mcf_container
    restart: always
    volumes:
      - /volume1/docker/MasterCryptoFarmBot:/app/MasterCryptoFarmBot
    environment:
      - PYTHONUNBUFFERED=1
    working_dir: /app/MasterCryptoFarmBot
    ports:
      - "3232:3232"
    networks:
      - default

    init: true
    entrypoint: >
      sh -c '
      if ! command -v git &> /dev/null; then
        apt-get update && apt-get install -y git;
      fi &&
      if [ ! -f main.py ]; then
        git clone https://github.com/masterking32/MasterCryptoFarmBot.git ./;
      fi &&
      chown -R root:root ./ &&
      if [ ! -f config.py ]; then
        cp config.py.sample config.py
      fi &&
      if [ -f start_linux.sh ]; then
        echo "Launching...";
        bash start_linux.sh;
      fi'

networks:
  default:
    driver: bridge

```

**Reply by Fy0urM** [reply]
working yml for container manager, tested on DSM 7.2.2-72806
project path `/volume1/docker`
after first run, setup config and restart container

<details>
<summary>docker-compose.yml</summary>

```yml
version: '3.8'

services:
  MCF_Container:
    image: python:3.12
    stdin_open: true
    tty: true
    command: /bin/bash
    container_name: MCF_Container
    restart: always
    volumes:
      - /volume1/docker:/app/MasterCryptoFarmBot
    environment:
      - PYTHONUNBUFFERED=1
    working_dir: /app/MasterCryptoFarmBot
    ports:
      - "3232:3232"
    networks:
      - default

    init: true
    entrypoint: >
      sh -c '
      if ! command -v git &> /dev/null; then
        echo "Installing\Updating git...";
        apt-get update && apt-get install -y git;
      fi &&
      if [ ! -d MasterCryptoFarmBot ]; then
        echo "Cloning repository...";
        git clone https://github.com/masterking32/MasterCryptoFarmBot.git;
      fi &&
      cd MasterCryptoFarmBot &&
      if [ ! -f config.py ]; then
        echo "Copying config from sample..."
        cp config.py.sample config.py
      fi &&
      if [ -f start_linux.sh ]; then
        echo "Launching...";
        bash start_linux.sh;
      fi'

networks:
  default:
    driver: bridge

```
</details>

<details>
<summary>screenshot</summary>

![image](https://github.com/user-attachments/assets/cd95fe15-99a2-4f24-b5d3-d92b61f4ce64)

</details>
